// Auto-generated by scripts/parse-kmz.ts
// Do not edit manually

import type { Restaurant } from '../types/restaurant';

// Restaurant data is loaded from JSON to avoid TypeScript complexity with large literal arrays
import restaurantsData from '../../public/data/restaurants.json';

export const restaurants = restaurantsData as Restaurant[];

export const restaurantCount = 1868;

// Pre-computed unique cities for filter dropdowns
export const cities: string[] = ["Busan","Daegu","Daejeon","Gangwon","Gwangju","Gyeonggi","Incheon","Jeju","Seoul","Ulsan"];

// Pre-computed categories
export const categories: string[] = ["accommodation","grocery","mosque","other","restaurant"];
